[[constraint]]
  name = "github.com/cloudflare/cloudflare-go"
  version = "0.8.4"

[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"